#!/bin/bash

if [ "$PRODUCTION" = "1" ]; then
    # PRODUCTION
    python3 -m gunicorn --config gunicorn.conf.py "tidbyt_manager:create_app()"
else
    # DEVELOPMENT
    FLASK_APP=tidbyt_manager FLASK_DEBUG=1 flask run --host=0.0.0.0 --port=8000
fi