#!/bin/bash
set -euo pipefail

if [ "${PRODUCTION:-1}" = "1" ]; then
    # PRODUCTION
    exec python3 -m gunicorn --config gunicorn.conf.py tronbyt_server.main:app
else
    # DEVELOPMENT
    exec uvicorn --host=0.0.0.0 --port=8000 --reload tronbyt_server.main:app
fi