"""Create user, device, and app tables"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d43d3af2d44"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("theme_preference", sa.String(), nullable=False),
        sa.Column("system_repo_url", sa.String(), nullable=False),
        sa.Column("app_repo_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "device",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("img_url", sa.String(), nullable=False),
        sa.Column("ws_url", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("brightness", sa.Integer(), nullable=False),
        sa.Column("night_mode_enabled", sa.Boolean(), nullable=False),
        sa.Column("night_mode_app", sa.String(), nullable=False),
        sa.Column("night_start", sa.String(), nullable=True),
        sa.Column("night_end", sa.String(), nullable=True),
        sa.Column("night_brightness", sa.Integer(), nullable=False),
        sa.Column("dim_time", sa.String(), nullable=True),
        sa.Column("dim_brightness", sa.Integer(), nullable=True),
        sa.Column("default_interval", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("location", sa.JSON(), nullable=True),
        sa.Column("last_app_index", sa.Integer(), nullable=False),
        sa.Column("pinned_app", sa.String(), nullable=True),
        sa.Column("interstitial_enabled", sa.Boolean(), nullable=False),
        sa.Column("interstitial_app", sa.String(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("info", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "app",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iname", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("uinterval", sa.Integer(), nullable=False),
        sa.Column("display_time", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("pushed", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("last_render", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("days", sa.JSON(), nullable=True),
        sa.Column("use_custom_recurrence", sa.Boolean(), nullable=False),
        sa.Column("recurrence_type", sa.String(), nullable=False),
        sa.Column("recurrence_interval", sa.Integer(), nullable=False),
        sa.Column("recurrence_pattern", sa.JSON(), nullable=True),
        sa.Column("recurrence_start_date", sa.Date(), nullable=True),
        sa.Column("recurrence_end_date", sa.Date(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("empty_last_render", sa.Boolean(), nullable=False),
        sa.Column("render_messages", sa.JSON(), nullable=True),
        sa.Column("autopin", sa.Boolean(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app")
    op.drop_table("device")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
